public with sharing class Body {

    public static String BODY = '[{"initiative_id":"58af4da0b310d92314627232","collector_id":"5db6ea277afecc0007c6205f","collector_name":"Sandbox Survey Collector","from_email":"kallred@primary-intel.com","date_created":"2019-10-28T13:16:23.114Z","date_survey_start":"2019-10-28T13:16:21.000Z","is_active":true,"time_zone":{"utc":"America/Boise","text":"(UTC-07:00) Mountain Time (US & Canada)"},"is_email_confirmed":true}]';
//    public static String BODYFAILED = '';


}